### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name": "Krishna Shrestha",
    "company": "Dented Code",
    "address": "Rockdale",
    "phone": 1234567890,
    "email": "krish_sth2005@yahoo.com",
    "password": "abc123"
}

### user login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "krish_sth2005@yahoo.com",
    "password": "abc12sss"
}