### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name": "Krishna Shrestha",
    "company": "Dented Code",
    "address": "Rockdale",
    "phone": 1234567890,
    "email": "krish_sth2005@yahoo.com",
    "password": "abc123"
}

### user login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "krish_sth2005@yahoo.com",
    "password": "abc123"
}

### Get a user profile endpoint
GET http://localhost:8000/api/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoia3Jpc2hfc3RoMjAwNUB5YWhvby5jb20iLCJpYXQiOjE2NjM5MTEzMDYsImV4cCI6MTY2MzkxMTM2Nn0.U1KjvWYaQ5nwbkvlriiqdO1NHRK-OeNEjMOd-76V_cc



### === Token router ===

### Get refreshed token jwt
GET http://localhost:8000/api/v1/tokens/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoia3Jpc2hfc3RoMjAwNUB5YWhvby5jb20iLCJpYXQiOjE2NjM5MTMxMTgsImV4cCI6MTY2NjUwNTExOH0.zANCYifsXIAC-pJzp9e3L2BfNGCrYikO4booy7sX5MA
