### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

{
    "name": "Krishna Shrestha",
    "company": "Dented Code",
    "address": "Rockdale",
    "phone": 1234567890,
    "email": "krish_sth2005@yahoo.com",
    "password": "abc123"
}

### user login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email": "krish_sth2005@yahoo.com",
    "password": "abc123"
}

### Get a user profile endpoint
GET http://localhost:8000/api/v1/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoia3Jpc2hfc3RoMjAwNUB5YWhvby5jb20iLCJpYXQiOjE2NjM2NzcwMjYsImV4cCI6MTY2MzY3NzkyNn0.yQoeGTHOwXnHWcgSBsJxbphLwJ9DqxKyYjOFJD0YrLI